---
# Instalacion de repositorios.
# tasks to install php8.2 Debian bulseye or Ubuntu focal
- name: Install php7.4
  apt: pkg={{ item }} state=present
  #Que items? selecciona los paquetes de la carpeta vars/main.yml, donde se indica php7.4 y la sección de packages
  with_items: "{{ php.packages.php74 }}"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bulseye") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_release'] == "focal")

# tasks to install php8.2 - Debian booworm
- name: Install php8.2
  apt: pkg={{ item }} state=present
  #Que items? selecciona los paquetes de la carpeta vars/main.yml, donde se indica php7.4 y la sección de packages
  with_items: "{{ php.packages.php82 }}"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bookworm")
